# Generated by Django 4.2.3 on 2023-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='dist',
            field=models.TextField(),
        ),
    ]
