# Generated by Django 4.2.3 on 2023-09-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_form_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.TextField(),
        ),
    ]
