# Generated by Django 4.2.3 on 2023-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_form_dist_alter_form_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='mat_pro',
            field=models.TextField(),
        ),
    ]
